sudo: required
services:
  - docker

before_install:
  - docker build -t vanderful/docker-react-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true vanderful/docker-react-frontend npm run test